console.log("Hello Winc Academy");
let name = 'Greet';
console.log(name);
let number1 = 4;
let number2 = 4;
console.log(number1 + number2);
const number3 = '4';
const number4 = '4';
console.log(number3 + number4);
const number5 = 5;
const number6 = 2;
const sum = number5 + number6;
console.log('The sum of ' + number5 + ' and ' + number6 + ' is ' + sum);
console.log(number5 + number6);
console.log(number5 - number6);
console.log(number5 * number6);
console.log(number5 / number6);
console.log(number5 % number6);
let age = '50';
console.log(typeof age);